### ISSUE TITLE
Contantly Getting "Already logged on" Errors and sudden connection losses inside DOCKER

### ISSUE THREAD

**Issue by Rodrigo-JM** [csfloat/inspect#181]
Can't really provide a way to reproduce since its just using the docker image inside cloud run (could be occuring in other services like this)

**Comment by Step7750** [comment]
Unfortunately there is not nearly enough info to debug anything here.

**Comment by Rodrigo-JM** [comment]
Yeah, It is probably related to mckay's lib anyway. Just posted here to see if It was a common issue people were dealing with
