### ISSUE TITLE
Error when logging in after Steam update

### ISSUE THREAD

**Issue by denghuols** [csfloat/inspect#186]
**Describe the bug**
Seems like after todays update (12/09/2023) something broke on the package, seems to be related to Polling, havent really investigated as of now.

Heres the output of the error:
this.debug is not a function

There seems to be a problem with the package node-steam-user.

Best Regards,

**Comment by dolac35** [comment]
https://github.com/DoctorMcKay/node-steam-user/releases/tag/v4.29.2

**Comment by denghuols** [comment]
> https://github.com/DoctorMcKay/node-steam-user/releases/tag/v4.29.2

Thank you for your reply!!
