### ISSUE TITLE
error when starting docker container

### ISSUE THREAD

**Issue by DJTaDJuk** [csfloat/inspect#196]
have this shen try to start container
![image](https://github.com/csfloat/inspect/assets/114240459/a1ee9bd1-eda0-4d97-9ddd-04bc2a5a514a)

tryed change proxies, update docker and container. It worked month ago, but now not. How can i solve this problem?

**Comment by lyeskin** [comment]
The same for me, it runs well on local machine, but fails on VPS

**Comment by lyeskin** [comment]
@DJTaDJuk probably your postgres server is not running

**Comment by dNhCm** [comment]
@lyeskin I have the same problem, but the postgres db is still working. But steam bots get offline too quickly..

**Comment by lyeskin** [comment]
@dNhCm I fixed it by restarting postgres container only, but you also can look for an  node-steam-user update (https://github.com/DoctorMcKay/node-steam-user/releases).
You should just update  `package.lock` in the current repository:
`globaloffensive` to version 3.0.0 and  `steam-user` to 5.0.7
Then build your own docker image and push it to your registry.
