### ISSUE TITLE
Sticker info

### ISSUE THREAD

**Issue by SvyatoslavArtymovych** [csfloat/inspect#197]
Hello. I remember the API was returning more information about stickers(name, wear) but now I have only stickerId and slot. Has the rest data been removed from the response? If not, how can I get it?

```
    "stickers": [
      {
        "stickerId": 4538,
        "slot": 3
      }
    ],
```
URL:
`steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20M4652848484126482244A35394143813D4812146788585465113`

**Comment by SvyatoslavArtymovych** [comment]
It also used to return the item name in iteminfo, but now it doesn't
Full response

`{
  "iteminfo": {
    "origin": 8,
    "quality": 4,
    "rarity": 4,
    "a": "35394143813",
    "d": "4812146788585465113",
    "paintseed": 386,
    "defindex": 7,
    "paintindex": 1035,
    "stickers": [
      {
        "stickerId": 4538,
        "slot": 3
      }
    ],
    "floatid": "35394143813",
    "low_rank": 1,
    "high_rank": 2,
    "floatvalue": 0.4011116921901703,
    "m": "4652848484126482244",
    "s": "0"
  }
}`

**Comment by menschma1er** [comment]
haven't looked into all the underlaying packages, but sending the message to the GC myself also returned less data than before. I would also be interested in where to get a mapping stickerId<->market_hash_name
