### ISSUE TITLE
Bots can't login properly

### ISSUE THREAD

**Issue by denghuols** [csfloat/inspect#198]
**Describe the bug**
When CS2 update today , i found my bots are all offline.And I can't login my bots anymore.the screenshot show the all bots "Got unhandled GC message 9187". I don't know how to fix this problem。And when i restart process, the info tell me that accouns login is OK.But i don't know why I get /stats ,all bots are offine.

**To Reproduce**
1. Restart the process

**Screenshots**
![3dbbd93223496a1949bbb441e7c0ffeb](https://github.com/csfloat/inspect/assets/52654558/0293e880-e82d-45b6-ba36-b40fa19837a2)

![ac0a244f051e8e61d28c6de3db0a7cab](https://github.com/csfloat/inspect/assets/52654558/a90603c6-8cb3-401c-b07f-6825acc17ae0)

Please tell my why my project happen this error ,thanks for your help！

**Comment by Tankonyako** [comment]
have same problem

**Comment by tima1906** [comment]
same

**Comment by vladdnepr** [comment]
same

**Comment by vladdnepr** [comment]
https://github.com/DoctorMcKay/node-globaloffensive/issues/85

**Comment by vladdnepr** [comment]
> k_EMsgGCCStrike15_v2_ClientLogonFatalError = 9187

https://github.com/SteamRE/SteamKit/blob/master/SteamKit2/SteamKit2/Base/Generated/GC/CSGO/MsgGC.cs

**Comment by nandychu** [comment]
same here

**Comment by RRocha21** [comment]
same here

**Comment by vladdnepr** [comment]
https://github.com/DoctorMcKay/node-globaloffensive/issues/85#issuecomment-1931689414

**Comment by vladdnepr** [comment]
https://github.com/DoctorMcKay/node-globaloffensive/pull/86

**Comment by denghuols** [comment]
> [DoctorMcKay/node-globaloffensive#86](https://github.com/DoctorMcKay/node-globaloffensive/pull/86)

Can you tell me how to  fix this bug for "inspect" Thank you very much!

**Comment by ForestSDA** [comment]
> перейдите в строку 120 node_modules\globaloffensive\index.js и измените ее на эту `this._send(Language.ClientHello, Protos.CMsgClientHello, { version: 2000202});`

![image](https://github.com/csfloat/inspect/assets/96347636/20d47186-ae22-4a8a-a8b2-367eea1681c9)

**Comment by denghuols** [comment]
> go into node_modules\globaloffensive\index.js line 120 and change it to this `this._send(Language.ClientHello, Protos.CMsgClientHello, { version: 2000202});`

Thanks for your help!

**Comment by wangxingzhen** [comment]
> go into node_modules\globaloffensive\index.js line 120 and change it to this `this._send(Language.ClientHello, Protos.CMsgClientHello, { version: 2000202});`

Very thanks for your help!!!!!!!!!

**Comment by Helyux** [comment]
If i see this correctly the node package in question (globaloffensive) has been updated to handle the gc message. ([ref](https://github.com/DoctorMcKay/node-globaloffensive/releases))

@Step7750 do you think it would be possible to just bump said package (also for the docker image)?
As far as i can tell the only breaking change from ^2.3 to ^3.0 would be that Node.js 14 is required now.
