### ISSUE TITLE
post /bulk working or not?

### ISSUE THREAD

**Issue by salamat711** [csfloat/inspect#214]
i get this error. Installed the bot locally.

HTTP/1.1 400 Bad Request
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 68
ETag: W/"44-EwaRAyxpbHhvAU2bYzTUkZuZf8k"
Date: Tue, 09 Apr 2024 04:05:18 GMT
Connection: keep-alive
Keep-Alive: timeout=5

{"error":"You have too many pending requests","code":3,"status":400}

**Comment by wangxingzhen** [comment]
I think you should provide more information to describe this problem. How many accounts have you configured? Is there a web proxy? What is max_simultaneous_requests in the configuration file?
