### ISSUE TITLE
Maybe stupid question about the IP

### ISSUE THREAD

**Issue by Magnus-T-Holm** [csfloat/inspect#215]
I have what might be a stupid question, but I haven't been able to get this to work fully and I want to make sure I'm not doing something wrong.

When I make a get requests with `http://<ip>:<port>/?url=...`, should the ip be "localhost" if I'm running it locally on my PC or should it be something else?
Also is the port the same port that we write in the config.js under `// Configuration for the HTTP API server`?

**Comment by wangxingzhen** [comment]
<ip> you can use 'localhost' or '127.0.0.1'

**Comment by wangxingzhen** [comment]
「Also is the port the same port that we write in the config.js under // Configuration for the HTTP API server?」 
  YES

**Comment by Magnus-T-Holm** [comment]
Okay, thank you for the information.

Then I guess I've messed something up with either postgreSQL or written something wrong in the config file.
