### ISSUE TITLE
Cannot query the API using inspect link

### ISSUE THREAD

**Issue by Podsah** [csfloat/inspect#218]
Hello, 

I have a trouble with calling the API using any inspect link. When I call http://192.168.0.2:60/stats everything is alright (I assume) and I get this response: {"bots_online":2,"bots_total":2,"queue_size":0,"queue_concurrency":2}
The problem is when I call any inspect link, e.g. 
http://192.168.0.2:60/?url=steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20M4860026836990897821A38189083877D12028068010305938751
It just takes forever and literally nothing happens. I do not get any error message or anything. Is it any known issue or I just messed something up?

Have a great day guys!

**Comment by Step7750** [comment]
Ensure that you setup the Postgres database: https://github.com/csfloat/inspect?tab=readme-ov-file#how-to-install
